### ISSUE TITLE
Fail to run the example data

### ISSUE THREAD

**Issue by zenghk** [jao321/YClon#1]
I am using YClon to test the cluster the clonotype with a large dataset, but I have some problems in the first step, I cannot run even using the example data in the *zip, I run 

```
python YClon.py YClon_input_test_airr_only_essential_info.tsv
and get YClon_input_test_airr_only_essential_info_YClon_clonotyped.tsv
however, the file YClon_input_test_airr_only_essential_info_YClon_clonotyped.tsv contain nothing except for a single row title,
```

The related enviroment of my platform is listed as below
Platform CentOS Linux release 7.9.2009 (Core)
Python version: anaconda/3-2021.11/bin/python3.9
alive_progress 2.3.1
pandas 1.3.4
numpy 1.22.3
sklearn 0.0
hdbscan 0.8.28
sparse-dot-topn 0.3.1
scikit-learn 0.24.2

Could you have a look at that?
Thanks.

**Comment by jao321** [comment]
Thank you for the feedback.

Unfortunately I could not reproduce this error. 
Even installing everything in a fresh computer, anaconda 3-2021.11, python3.9.

But I remove the import of hdbscan and sparse-dot-topn, since in the more recent version they are not needed.

![python_packages](https://user-images.githubusercontent.com/50146651/157881365-2c9ade6c-28ab-4f06-86a2-92c59933f34a.png)
![yclon_running](https://user-images.githubusercontent.com/50146651/157881370-453943d9-75ab-4f31-835f-25fe24148045.png)

I manage to put together a Google Colab notebook, in it you can run the example data. There is also the possibility of uploading your own data in a more "intuitive" manner, although it takes a long time to upload files.

https://colab.research.google.com/drive/1vQFF8e2hxMAeDSJNooVx6zaJ2hzPVbuH?usp=sharing

Just reminding that it runs in python3, but not in python2.

**Comment by zenghk** [comment]
Thanks for your reply, 
According to your suggestion, I re-run the script by updating the script to the newest version or using a virtual environment with python3.7 to run the script, however, neither of them works. But when I test the script on my laptop with windows, it works well, so I think there may be something wrong with my HPC environment, and I ask the engineer for help now.

**Comment by zenghk** [comment]
Thanks for your reply, 
According to your suggestion, I re-run the script by updating the script to the newest version or using a virtual environment with python3.7 to run the script, however, neither of them works. But when I test the script on my laptop with windows, it works well, so I think there may be something wrong with my HPC environment, and I ask the engineer for help now.
