### ISSUE TITLE
Different Distance Calculation Methods Selection 

### ISSUE THREAD

**Issue by yirenheihei** [jao321/YClon#3]
Hello, I have reread your article and I have some confusion regarding the distance calculation method used for clustering. When I calculate the distance between seq1="CGSNRKGYLHLSNSDDYN" and seq2="CGSNRKGYLHLRNSDDYN", these two sequences only differ by one amino acid, resulting in a Hamming distance of 0.056. However, when I calculate the distance using your method, I find that the distance between these two sequences is 0.1875. If I choose the default threshold of 0.09, then these two sequences would not be considered as the same clonotype. I would like to inquire about the reason why you did not use the Hamming distance in this case.I am lLooking forward to your reply. Thank you

**Comment by jao321** [comment]
Hi,

My method was only tested with distances between nucleotides and not amino acids. Although it should work fine with amino acid, I would not advise to do so. Because the shorter the sequence, the skewer are the results.

I do not align the sequence, therefore, I cannot say for sure that their difference can be compared using only the hamming distance. As the difference they have might be the result of insertions and deletions. If the difference is only one nucleotide between only two sequences, it seems obvious that the difference is due to a mutation in that specific nucleotide. But when there are more than just one and throughout several thousands sequences, it is not that clear.

The threshold of 0.09 regards their cosine dissimilarity (1-cosine similarity), when comparing the resulting vectors of their ngram composition. The metric is a little different. 

When I reverse translate the sequences you suggested, by the most probable codon usage, I got theses DNA sequences: 
'tgcggcagcaaccgcaaaggctatctgcatctgcgcaacagcgatgattataactaa'
'tgcggcagcaaccgcaaaggctatctgcatctgagcaacagcgatgattataactaa'

Their hamming distance is 0.018. By employing my method, their cosine dissimilarity result in 0.02507238. Thus, they would be grouped in the same clonotype.

**Comment by yirenheihei** [comment]
Thank you for your prompt reply. I really appreciate it. I will try.
